[package]
name = "env_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = "*"
rand = "*"

[lib]
name = "env_sim"
path = "src/lib.rs"
crate-type = ["cdylib"]
